# Generated by Django 5.2.2 on 2025-10-28 02:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Plantacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_finca', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('extension_hectareas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_analisis/')),
                ('contorno', models.ImageField(blank=True, null=True, upload_to='imagenes_analisis/contornos/')),
                ('overlay', models.ImageField(blank=True, null=True, upload_to='imagenes_analisis/overlay/')),
                ('damage', models.ImageField(blank=True, null=True, upload_to='imagenes_analisis/dano/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('plantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.plantacion')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaComunitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.CharField(max_length=100)),
                ('distancia', models.FloatField(help_text='Distancia en km')),
                ('fecha_alerta', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_emitidas', to=settings.AUTH_USER_MODEL)),
                ('plantacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_generadas', to='core.plantacion')),
            ],
            options={
                'verbose_name': 'Alerta Comunitaria',
                'verbose_name_plural': 'Alertas Comunitarias',
                'ordering': ['-fecha_alerta'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('temperatura', models.DecimalField(decimal_places=1, help_text='Temperatura en °C', max_digits=4)),
                ('humedad', models.DecimalField(decimal_places=2, help_text='Humedad relativa en %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('precipitacion', models.DecimalField(decimal_places=2, help_text='Precipitación en mm', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('ph_suelo', models.DecimalField(decimal_places=1, help_text='pH del suelo', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('humedad_suelo', models.DecimalField(decimal_places=2, help_text='Humedad del suelo en %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nitrogeno', models.DecimalField(decimal_places=2, help_text='Nitrógeno en ppm', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('actividad_realizada', models.CharField(blank=True, choices=[('fertilizacion', 'Fertilización'), ('riego', 'Riego'), ('cosecha', 'Cosecha'), ('poda', 'Poda'), ('otro', 'Otro')], max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_campo', to='core.plantacion')),
            ],
            options={
                'verbose_name': 'Registro de Campo',
                'verbose_name_plural': 'Registros de Campo',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad_detectada', models.CharField(max_length=100)),
                ('probabilidad', models.FloatField()),
                ('recomendaciones', models.TextField()),
                ('informe_pdf', models.FileField(blank=True, null=True, upload_to='informes/')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='core.imagenanalisis')),
            ],
        ),
    ]
